[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NETLIFY_USE_NPM_CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "https://connectra-btxb.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
