import React, { useState, useEffect, useRef } from 'react';
import { Phone, PhoneOff, Video, VideoOff, Mic, MicOff, ShieldAlert, RefreshCw, UserPlus, Share2 } from 'lucide-react';

// Sub-component to bind and render remote user stream
function RemoteVideo({ stream, username }) {
  const videoRef = useRef(null);

  useEffect(() => {
    if (videoRef.current && stream) {
      videoRef.current.srcObject = stream;
    }
  }, [stream]);

  return (
    <div className="remote-video-container">
      <video ref={videoRef} autoPlay playsInline className="remote-video" />
      <div className="remote-video-label">{username}</div>
    </div>
  );
}

export default function CallModal({
  socket,
  token,
  userId,
  username,
  contact,
  callType, // 'audio' or 'video'
  roomId, // unique room ID generated by initiator
  contacts = [],
  onlineStatuses = {},
  incomingOffer, // if incoming call
  callerName, // if incoming call
  isIncomingInit, // true if callee is receiving call
  onCallFinished,
  onClose
}) {
  const [callState, setCallState] = useState(isIncomingInit ? 'incoming' : 'ringing');
  const [localStream, setLocalStream] = useState(null);
  const [remoteStreams, setRemoteStreams] = useState({}); // mapped by socketId: { userId, username, stream }
  
  const [isMuted, setIsMuted] = useState(false);
  const [isCamOff, setIsCamOff] = useState(callType === 'audio');
  const [facingMode, setFacingMode] = useState('user');
  const [errorMessage, setErrorMessage] = useState('');
  
  // Invite panel state
  const [showInviteDropdown, setShowInviteDropdown] = useState(false);
  const [inviteFeedback, setInviteFeedback] = useState('');

  // Subtitles state & refs
  const [subtitles, setSubtitles] = useState([]);
  const recognitionRef = useRef(null);
  const isMutedRef = useRef(isMuted);

  // Screen sharing states & refs
  const [isScreenSharing, setIsScreenSharing] = useState(false);
  const screenStreamRef = useRef(null);

  const peerConnectionsRef = useRef({}); // mapped by socketId
  const pendingIceCandidatesRef = useRef({}); // mapped by socketId: [candidates]
  const localVideoRef = useRef(null);
  const callStartTimeRef = useRef(null);
  const localStreamRef = useRef(null);
  const joinedRoomRef = useRef(false);

  const callStateRef = useRef(callState);
  useEffect(() => {
    callStateRef.current = callState;
    if (callState === 'connected' && !callStartTimeRef.current) {
      callStartTimeRef.current = Date.now();
    }
  }, [callState]);

  // Handle Speech-to-Text Recognition on call connection
  useEffect(() => {
    isMutedRef.current = isMuted;
    if (recognitionRef.current) {
      if (isMuted) {
        try { recognitionRef.current.stop(); } catch(e) {}
      } else {
        try { recognitionRef.current.start(); } catch(e) {}
      }
    }
  }, [isMuted]);

  useEffect(() => {
    let rec = null;
    if (callState === 'connected') {
      const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
      if (SpeechRecognition) {
        rec = new SpeechRecognition();
        rec.continuous = true;
        rec.interimResults = true;
        rec.lang = 'en-US';
        
        rec.onresult = (event) => {
          let interimTranscript = '';
          let finalTranscript = '';
          for (let i = event.resultIndex; i < event.results.length; ++i) {
            if (event.results[i].isFinal) {
              finalTranscript += event.results[i][0].transcript;
            } else {
              interimTranscript += event.results[i][0].transcript;
            }
          }
          const transcript = finalTranscript || interimTranscript;
          if (transcript.trim() && !isMutedRef.current) {
            socket.emit('call_subtitles', {
              roomId,
              senderName: username,
              text: transcript
            });
          }
        };
        
        rec.onerror = (e) => {
          console.error('Speech recognition error:', e);
        };
        
        rec.onend = () => {
          if (callStateRef.current === 'connected' && !isMutedRef.current && recognitionRef.current) {
            try {
              recognitionRef.current.start();
            } catch (err) {}
          }
        };
        
        recognitionRef.current = rec;
        if (!isMutedRef.current) {
          try {
            rec.start();
          } catch(e) {}
        }
      } else {
        console.warn('SpeechRecognition is not supported in this browser.');
      }
    }
    
    return () => {
      if (rec) {
        try {
          rec.abort();
        } catch(e) {}
      }
      recognitionRef.current = null;
    };
  }, [callState]);

  // Periodically clear old subtitles (older than 5 seconds)
  useEffect(() => {
    const interval = setInterval(() => {
      setSubtitles(prev => prev.filter(s => Date.now() - s.timestamp < 5000));
    }, 1000);
    return () => clearInterval(interval);
  }, []);

  // Bind local stream to video element
  useEffect(() => {
    if (localVideoRef.current && localStream) {
      localVideoRef.current.srcObject = localStream;
    }
  }, [localStream, callState]);

  // Auto disconnect handled inside handleUserLeftCall to prevent race conditions during setup

  // Setup local media stream
  useEffect(() => {
    let activeStream = null;
    let isCancelled = false;

    const setupMedia = async () => {
      try {
        const constraints = {
          audio: true,
          video: callType === 'video' ? { facingMode: 'user' } : false
        };
        const stream = await navigator.mediaDevices.getUserMedia(constraints);
        if (isCancelled) {
          stream.getTracks().forEach(track => track.stop());
          return;
        }
        activeStream = stream;
        setLocalStream(stream);
        localStreamRef.current = stream;

        if (!isIncomingInit) {
          // Join room and start dialing callee
          socket.emit('join_call_room', { roomId, userId, username });
          joinedRoomRef.current = true;
          
          if (contact.isGroup) {
            socket.emit('call_group', {
              groupId: contact.groupId,
              roomId,
              signalData: { roomId },
              type: callType
            });
          } else {
            socket.emit('call_user', {
              userToCall: contact.id,
              signalData: { roomId },
              from: userId,
              type: callType
            });
          }
        }
      } catch (err) {
        console.error('Failed to get media devices:', err);
        if (!isCancelled) {
          setErrorMessage('Permission denied or devices not found. Please check permissions.');
        }
      }
    };

    setupMedia();

    return () => {
      isCancelled = true;
      if (activeStream) {
        activeStream.getTracks().forEach(track => track.stop());
      }
      if (localStreamRef.current) {
        localStreamRef.current.getTracks().forEach(track => track.stop());
      }
      if (screenStreamRef.current) {
        screenStreamRef.current.getTracks().forEach(track => track.stop());
      }
      
      // Close all peer connections
      Object.values(peerConnectionsRef.current).forEach(pc => pc.close());
      peerConnectionsRef.current = {};
      
      if (socket && joinedRoomRef.current) {
        socket.emit('leave_call_room', { roomId });
      }
    };
  }, []);

  // Handle incoming socket signals for room
  useEffect(() => {
    if (!socket) return;

    // Triggered when someone accepts the 1-to-1 dial
    const handleCallAccepted = (data) => {
      console.log('📞 Outgoing call accepted!');
      setCallState('connected');
    };

    // Triggered when call is declined
    const handleCallRejected = () => {
      console.log('📞 Call rejected by recipient');
      setCallState('disconnected');
      if (!isIncomingInit && onCallFinished) {
        onCallFinished({ type: callType, status: 'missed', duration: 0 });
      }
      setTimeout(() => onClose(), 1500);
    };

    // Call Ended (for cancelling / 1-to-1 disconnects)
    const handleCallEnded = () => {
      console.log('📞 Call ended by remote peer');
      setCallState('disconnected');
      if (!isIncomingInit && onCallFinished) {
        let duration = 0;
        if (callStartTimeRef.current) {
          duration = Math.floor((Date.now() - callStartTimeRef.current) / 1000);
        }
        onCallFinished({
          type: callType,
          status: callStartTimeRef.current ? 'connected' : 'missed',
          duration
        });
      }
      setTimeout(() => onClose(), 1000);
    };

    // User joined the room
    const handleUserJoinedCall = async (data) => {
      const { userId: joinUserId, username: joinUsername, socketId } = data;
      console.log(`👤 Participant joined: ${joinUsername} | Socket: ${socketId}`);
      setCallState('connected');

      // Create new peer connection for this newcomer
      const pc = createPeerConnection(socketId, joinUserId, joinUsername);
      try {
        const offer = await pc.createOffer();
        await pc.setLocalDescription(offer);
        socket.emit('room_signal', {
          roomId,
          targetSocketId: socketId,
          signalData: offer
        });
      } catch (err) {
        console.error('Error creating offer for new participant:', err);
      }
    };

    // User left the room
    const handleUserLeftCall = (data) => {
      const { socketId } = data;
      console.log(`👤 Participant left socket: ${socketId}`);
      
      if (peerConnectionsRef.current[socketId]) {
        peerConnectionsRef.current[socketId].close();
        delete peerConnectionsRef.current[socketId];
      }
      
      setRemoteStreams(prev => {
        const copy = { ...prev };
        delete copy[socketId];
        
        // Only end the call if we were connected to some remote participants, and now there are none.
        if (callStateRef.current === 'connected' && Object.keys(copy).length === 0) {
          console.log('📞 All remote participants left. Ending call.');
          setTimeout(() => {
            endCall();
          }, 50);
        }
        
        return copy;
      });
    };

    // WebRTC signaling relay between room peers
    const handleRoomSignal = async (data) => {
      const { senderSocketId, senderUserId, senderUsername, signalData } = data;
      let pc = peerConnectionsRef.current[senderSocketId];

      try {
        if (signalData.type === 'offer') {
          console.log(`📞 Received SDP Offer from socket: ${senderSocketId}`);
          setCallState('connected');
          
          if (!pc) {
            pc = createPeerConnection(senderSocketId, senderUserId, senderUsername);
          }
          await pc.setRemoteDescription(new RTCSessionDescription(signalData));
          
          const answer = await pc.createAnswer();
          await pc.setLocalDescription(answer);
          
          socket.emit('room_signal', {
            roomId,
            targetSocketId: senderSocketId,
            signalData: answer
          });

          // Process queued candidates
          const queue = pendingIceCandidatesRef.current[senderSocketId];
          if (queue && queue.length > 0) {
            while (queue.length > 0) {
              const candidate = queue.shift();
              await pc.addIceCandidate(candidate);
            }
          }
        } else if (signalData.type === 'answer') {
          console.log(`📞 Received SDP Answer from socket: ${senderSocketId}`);
          if (pc) {
            await pc.setRemoteDescription(new RTCSessionDescription(signalData));
            
            // Process queued candidates
            const queue = pendingIceCandidatesRef.current[senderSocketId];
            if (queue && queue.length > 0) {
              while (queue.length > 0) {
                const candidate = queue.shift();
                await pc.addIceCandidate(candidate);
              }
            }
          }
        } else if (signalData.type === 'candidate') {
          const candidate = new RTCIceCandidate(signalData.candidate);
          if (pc && pc.remoteDescription) {
            await pc.addIceCandidate(candidate);
          } else {
            if (!pendingIceCandidatesRef.current[senderSocketId]) {
              pendingIceCandidatesRef.current[senderSocketId] = [];
            }
            pendingIceCandidatesRef.current[senderSocketId].push(candidate);
          }
        }
      } catch (err) {
        console.error('Failed to handle room WebRTC signal:', err);
      }
    };

    const handleCallSubtitlesReceived = (data) => {
      setSubtitles(prev => {
        const filtered = prev.filter(s => s.senderName !== data.senderName);
        return [...filtered, {
          senderName: data.senderName,
          text: data.text,
          timestamp: Date.now()
        }];
      });
    };

    socket.on('call_accepted', handleCallAccepted);
    socket.on('call_rejected', handleCallRejected);
    socket.on('user_joined_call', handleUserJoinedCall);
    socket.on('user_left_call', handleUserLeftCall);
    socket.on('room_signal', handleRoomSignal);
    socket.on('call_ended', handleCallEnded);
    socket.on('call_subtitles_received', handleCallSubtitlesReceived);

    return () => {
      socket.off('call_accepted', handleCallAccepted);
      socket.off('call_rejected', handleCallRejected);
      socket.off('user_joined_call', handleUserJoinedCall);
      socket.off('user_left_call', handleUserLeftCall);
      socket.off('room_signal', handleRoomSignal);
      socket.off('call_ended', handleCallEnded);
      socket.off('call_subtitles_received', handleCallSubtitlesReceived);
    };
  }, [socket, roomId]);

  // Create RTCPeerConnection for a room socket
  const createPeerConnection = (socketId, peerUserId, peerUsername) => {
    const pc = new RTCPeerConnection({
      iceServers: [{ urls: 'stun:stun.l.google.com:19302' }]
    });

    // Add local tracks
    if (localStreamRef.current) {
      localStreamRef.current.getTracks().forEach(track => {
        pc.addTrack(track, localStreamRef.current);
      });
    }

    // ICE Candidate
    pc.onicecandidate = (event) => {
      if (event.candidate) {
        socket.emit('room_signal', {
          roomId,
          targetSocketId: socketId,
          signalData: { type: 'candidate', candidate: event.candidate }
        });
      }
    };

    // Remote Track Arrived
    pc.ontrack = (event) => {
      console.log(`🎥 Received remote video track from: ${peerUsername}`);
      const stream = event.streams[0];
      setRemoteStreams(prev => ({
        ...prev,
        [socketId]: {
          userId: peerUserId,
          username: peerUsername,
          stream
        }
      }));
    };

    peerConnectionsRef.current[socketId] = pc;
    return pc;
  };

  // Callee: Accept incoming call
  const acceptCall = async () => {
    setCallState('connected');
    try {
      // Connect to socket room
      socket.emit('join_call_room', { roomId, userId, username });
      joinedRoomRef.current = true;
      socket.emit('accept_call', { to: contact.id, signalData: { roomId } });
    } catch (err) {
      console.error('Error accepting call:', err);
      setErrorMessage('Could not connect. Please check device permissions.');
      socket.emit('reject_call', { to: contact.id });
    }
  };

  // Callee: Decline incoming call
  const declineCall = () => {
    socket.emit('reject_call', { to: contact.id });
    onClose();
  };

  // End Call
  const endCall = () => {
    socket.emit('end_call', { to: contact.id });
    
    if (localStream) {
      localStream.getTracks().forEach(track => track.stop());
    }
    
    Object.values(peerConnectionsRef.current).forEach(pc => pc.close());
    peerConnectionsRef.current = {};

    socket.emit('leave_call_room', { roomId });

    if (!isIncomingInit && onCallFinished) {
      let duration = 0;
      if (callStartTimeRef.current) {
        duration = Math.floor((Date.now() - callStartTimeRef.current) / 1000);
      }
      onCallFinished({
        type: callType,
        status: callStartTimeRef.current ? 'connected' : 'missed',
        duration
      });
    }
    
    onClose();
  };

  // Switch Camera Track dynamically
  const switchCamera = async () => {
    if (!localStream || callType !== 'video') return;
    const newFacingMode = facingMode === 'user' ? 'environment' : 'user';
    setFacingMode(newFacingMode);
    
    try {
      const videoTrack = localStream.getVideoTracks()[0];
      if (videoTrack) {
        videoTrack.stop();
        localStream.removeTrack(videoTrack);
      }

      const constraints = {
        audio: false,
        video: { facingMode: newFacingMode }
      };
      
      const newStream = await navigator.mediaDevices.getUserMedia(constraints);
      const newVideoTrack = newStream.getVideoTracks()[0];
      localStream.addTrack(newVideoTrack);
      
      // Update local stream state
      const updatedStream = new MediaStream(localStream.getTracks());
      setLocalStream(updatedStream);
      localStreamRef.current = updatedStream;

      // Swap track in all RTCPeerConnections
      const pcs = Object.values(peerConnectionsRef.current);
      for (const pc of pcs) {
        const senders = pc.getSenders();
        const videoSender = senders.find(sender => sender.track && sender.track.kind === 'video');
        if (videoSender) {
          await videoSender.replaceTrack(newVideoTrack);
        }
      }
      console.log(`📷 Camera track swapped successfully. facingMode: ${newFacingMode}`);
    } catch (err) {
      console.error('Failed to switch camera:', err);
      setErrorMessage('Could not access alternative camera device.');
    }
  };

  const toggleScreenShare = async () => {
    if (isScreenSharing) {
      stopScreenShare();
    } else {
      try {
        const screenStream = await navigator.mediaDevices.getDisplayMedia({ video: true });
        screenStreamRef.current = screenStream;
        const screenTrack = screenStream.getVideoTracks()[0];

        screenTrack.onended = () => {
          stopScreenShare();
        };

        if (localStreamRef.current) {
          const cameraTrack = localStreamRef.current.getVideoTracks()[0];
          if (cameraTrack) {
            localStreamRef.current.removeTrack(cameraTrack);
            cameraTrack.stop();
          }
          localStreamRef.current.addTrack(screenTrack);
          
          const updatedStream = new MediaStream(localStreamRef.current.getTracks());
          setLocalStream(updatedStream);
          localStreamRef.current = updatedStream;
        }

        const pcs = Object.values(peerConnectionsRef.current);
        for (const pc of pcs) {
          const senders = pc.getSenders();
          const videoSender = senders.find(sender => sender.track && sender.track.kind === 'video');
          if (videoSender) {
            await videoSender.replaceTrack(screenTrack);
          }
        }

        setIsScreenSharing(true);
      } catch (err) {
        console.error('Failed to start screen share:', err);
      }
    }
  };

  const stopScreenShare = async () => {
    if (screenStreamRef.current) {
      screenStreamRef.current.getTracks().forEach(track => track.stop());
      screenStreamRef.current = null;
    }

    try {
      const constraints = { video: { facingMode: 'user' } };
      const cameraStream = await navigator.mediaDevices.getUserMedia(constraints);
      const cameraTrack = cameraStream.getVideoTracks()[0];

      if (localStreamRef.current) {
        const screenTrack = localStreamRef.current.getVideoTracks()[0];
        if (screenTrack) {
          localStreamRef.current.removeTrack(screenTrack);
        }
        localStreamRef.current.addTrack(cameraTrack);

        const updatedStream = new MediaStream(localStreamRef.current.getTracks());
        setLocalStream(updatedStream);
        localStreamRef.current = updatedStream;
      }

      const pcs = Object.values(peerConnectionsRef.current);
      for (const pc of pcs) {
        const senders = pc.getSenders();
        const videoSender = senders.find(sender => sender.track && sender.track.kind === 'video');
        if (videoSender) {
          await videoSender.replaceTrack(cameraTrack);
        }
      }
    } catch (err) {
      console.error('Failed to restore camera stream:', err);
      setErrorMessage('Could not restore camera stream.');
    }

    setIsScreenSharing(false);
  };

  // Toggles Mute & Camera
  const toggleMute = () => {
    if (localStream) {
      const audioTrack = localStream.getAudioTracks()[0];
      if (audioTrack) {
        audioTrack.enabled = !audioTrack.enabled;
        setIsMuted(!audioTrack.enabled);
      }
    }
  };

  const toggleCamera = () => {
    if (localStream && callType === 'video') {
      const videoTrack = localStream.getVideoTracks()[0];
      if (videoTrack) {
        videoTrack.enabled = !videoTrack.enabled;
        setIsCamOff(!videoTrack.enabled);
      }
    }
  };

  // Invite user to group call
  const inviteContactToCall = (contactToInvite) => {
    setShowInviteDropdown(false);
    console.log(`📞 Sending call invitation to: ${contactToInvite.username}`);
    
    // Dial invited user
    socket.emit('call_user', {
      userToCall: contactToInvite.id,
      signalData: { roomId },
      from: userId,
      type: callType
    });

    setInviteFeedback(`Invited ${contactToInvite.username}`);
    setTimeout(() => setInviteFeedback(''), 2500);
  };

  // Calculate user IDs already inside call to filter invite list
  const activeUserIdsInCall = [
    contact.id,
    userId,
    ...Object.values(remoteStreams).map(s => s.userId)
  ];

  // List of online contacts who are not already in the call
  const inviteableContacts = contacts.filter(c => 
    onlineStatuses[c.id] === 'online' && 
    !activeUserIdsInCall.includes(c.id)
  );

  if (errorMessage) {
    return (
      <div className="call-modal-overlay">
        <div className="call-card error glass-card">
          <ShieldAlert size={48} className="text-red animate-bounce" />
          <h3>Call Error</h3>
          <p>{errorMessage}</p>
          <button onClick={onClose} className="call-btn end-btn mt-4">Close</button>
        </div>
      </div>
    );
  }

  return (
    <div className="call-modal-overlay">
      {inviteFeedback && (
        <div className="invite-feedback-toast">{inviteFeedback}</div>
      )}

      {callState === 'incoming' && (
        <div className="call-card incoming glass-card">
          <div className="call-avatar animate-pulse">
            {callerName ? callerName[0].toUpperCase() : 'C'}
          </div>
          <h3>Incoming {callType === 'video' ? 'Video' : 'Audio'} Call</h3>
          <p>{callerName} is calling you...</p>
          <div className="call-decision-buttons">
            <button onClick={declineCall} className="call-decision-btn decline" title="Decline">
              <PhoneOff size={22} />
            </button>
            <button onClick={acceptCall} className="call-decision-btn accept" title="Accept">
              {callType === 'video' ? <Video size={22} /> : <Phone size={22} />}
            </button>
          </div>
        </div>
      )}

      {callState === 'ringing' && (
        <div className="call-card ringing glass-card">
          <div className="call-avatar animate-pulse">
            {contact.username ? contact.username[0].toUpperCase() : 'C'}
          </div>
          <h3>Ringing...</h3>
          <p>Calling {contact.username} ({callType === 'video' ? 'video' : 'audio'})</p>
          <button onClick={endCall} className="call-decision-btn decline" title="Cancel Call">
            <PhoneOff size={22} />
          </button>
        </div>
      )}

      {callState === 'disconnected' && (
        <div className="call-card ringing glass-card">
          <div className="call-avatar">
            {contact.username ? contact.username[0].toUpperCase() : 'C'}
          </div>
          <h3>Disconnected</h3>
          <p>Call finished.</p>
        </div>
      )}

      {callState === 'connected' && (
        <div className="active-call-layout">
          {/* Main Display: Grid of Remote Streams */}
          <div className="main-video-container">
            {callType === 'video' ? (
              Object.keys(remoteStreams).length > 0 ? (
                <div className={`video-grid size-${Object.keys(remoteStreams).length}`}>
                  {Object.entries(remoteStreams).map(([socketId, data]) => (
                    <RemoteVideo 
                      key={socketId} 
                      stream={data.stream} 
                      username={data.username} 
                    />
                  ))}
                </div>
              ) : (
                <div className="audio-call-fallback">
                  <div className="pulsing-call-avatar animate-pulse">
                    {contact.username ? contact.username[0].toUpperCase() : 'C'}
                  </div>
                  <h3>Connecting streams...</h3>
                  <p>Waiting for {contact.username} to bind video feed...</p>
                </div>
              )
            ) : (
              <div className="audio-call-fallback">
                <div className="pulsing-call-avatar animate-pulse">
                  {contact.username ? contact.username[0].toUpperCase() : 'C'}
                </div>
                <h3>{contact.username}</h3>
                <p>Voice Connected</p>
                {Object.keys(remoteStreams).length > 0 && (
                  <span className="conference-badge">Conference Call ({Object.keys(remoteStreams).length + 1} users)</span>
                )}
              </div>
            )}
          </div>

          {/* Picture-in-Picture Local Stream */}
          {callType === 'video' && localStream && !isCamOff && (
            <div className="local-video-pip glass-card">
              <video ref={localVideoRef} autoPlay muted playsInline className="local-video" />
            </div>
          )}

          {/* Subtitles Overlay */}
          {subtitles.length > 0 && (
            <div className="call-subtitles-overlay" style={{
              position: 'absolute',
              bottom: '100px',
              left: '50%',
              transform: 'translateX(-50%)',
              width: '80%',
              maxWidth: '600px',
              zIndex: 10,
              display: 'flex',
              flexDirection: 'column',
              gap: '6px',
              alignItems: 'center',
              pointerEvents: 'none'
            }}>
              {subtitles.map((sub, idx) => (
                <div 
                  key={idx} 
                  className="call-subtitle-bubble glass-card animate-zoom-in"
                  style={{
                    background: 'rgba(0, 0, 0, 0.65)',
                    border: '1px solid rgba(255, 255, 255, 0.15)',
                    borderRadius: '8px',
                    padding: '8px 14px',
                    color: '#fff',
                    fontSize: '0.85rem',
                    textAlign: 'center',
                    boxShadow: '0 4px 12px rgba(0,0,0,0.5)',
                    wordBreak: 'break-word',
                    lineHeight: '1.4'
                  }}
                >
                  <span style={{ fontWeight: 'bold', color: 'var(--primary-glow)', marginRight: '6px' }}>{sub.senderName}:</span>
                  {sub.text}
                </div>
              ))}
            </div>
          )}

          {/* Controls Overlay */}
          <div className="call-controls-overlay glass-card">
            <button
              onClick={toggleMute}
              className={`call-control-btn ${isMuted ? 'active-mute' : ''}`}
              title={isMuted ? 'Unmute microphone' : 'Mute microphone'}
            >
              {isMuted ? <MicOff size={20} /> : <Mic size={20} />}
            </button>

            {callType === 'video' && (
              <>
                <button
                  onClick={toggleCamera}
                  className={`call-control-btn ${isCamOff ? 'active-mute' : ''}`}
                  title={isCamOff ? 'Start Camera' : 'Stop Camera'}
                >
                  {isCamOff ? <VideoOff size={20} /> : <Video size={20} />}
                </button>

                <button
                  onClick={switchCamera}
                  className="call-control-btn"
                  title="Switch Camera (Front/Rear)"
                >
                  <RefreshCw size={20} />
                </button>

                <button
                  onClick={toggleScreenShare}
                  className={`call-control-btn ${isScreenSharing ? 'active-mute' : ''}`}
                  title={isScreenSharing ? 'Stop Screen Share' : 'Share Screen'}
                >
                  <Share2 size={20} />
                </button>
              </>
            )}

            {/* Invite button for conference calls */}
            <div className="call-invite-container">
              <button
                onClick={() => setShowInviteDropdown(!showInviteDropdown)}
                className={`call-control-btn ${showInviteDropdown ? 'active-mute' : ''}`}
                title="Invite someone to group call"
              >
                <UserPlus size={20} />
              </button>
              
              {showInviteDropdown && (
                <div className="invite-dropdown glass-card">
                  <div className="invite-dropdown-title">Invite Contact</div>
                  {inviteableContacts.length > 0 ? (
                    inviteableContacts.map(c => (
                      <button
                        key={c.id}
                        onClick={() => inviteContactToCall(c)}
                        className="invite-contact-item"
                      >
                        <div className="invite-contact-avatar">
                          {c.username[0].toUpperCase()}
                        </div>
                        <span>{c.username}</span>
                      </button>
                    ))
                  ) : (
                    <div className="invite-empty-state">
                      No other online contacts available.
                    </div>
                  )}
                </div>
              )}
            </div>

            <button
              onClick={endCall}
              className="call-control-btn hang-up-btn"
              title="Hang up"
            >
              <PhoneOff size={20} />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
